### ISSUE TITLE
Ideas for June release

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2120]
Not an issue, just want to sync up on future plans, since we don't have a meeting until next Monday.

Now that 2.2.0 is out (congrats everyone!), here's what I was thinking of tackling in time for 2.3.0:

High priority:
- [ ] persistent map/reduce sugar, need to design a crazy-good API to make this painless for users (#2017) 
- [x] MemDOWN/LocalStorage adapters.  I don't know if I'll be the one to do that, though; @calvinmetcalf and @daleharvey are more experienced with browserify/config/build stuff, and that's pretty much all that's left.

Medium priority:
- [ ] unversioned local docs. Will sync up with @calvinmetcalf on this, requires a migration in all adapters but the implementation for Level is already written (#2061) 
- [ ] stable tests in Cordova/Safari/iOS.  I want us to stop having to worry about WebSQL for awhile. Judging by the failures, I may start writing PRs for the [SQLite plugin](https://github.com/brodysoft/Cordova-SQLitePlugin).

Low priority:
- [ ] speed up auto_compaction to make map/reduce faster (#2010)

That's what's on my top of mind. What's everybody else interested in doing, and did I miss anything?
