### ISSUE TITLE
Tracking November tasks

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#2986]
Just gonna use this space to track what I plan on working on in November and December; feel free to comment or add your own tasks.

* [ ] parallellize `allDocs()` for IDB (https://github.com/pouchdb/pouchdb/issues/2633)
* [ ] in-memory keys for IndexedDB (probably a separate module)
* [ ] filtered replication with a server-side filter function (#2232)
* [ ] purge (#802)
* [ ] slow replication (#2940 and ongoing pouchdb-replication-stream stuff)
* [ ] replication in two tabs at once (https://github.com/pouchdb/pouchdb/issues/2493)
* [ ] video tutorials

**Comment by daleharvey** [comment]
So november happened
