### ISSUE TITLE
RFC: Tracking idb-next release work

### ISSUE THREAD

**Issue by daleharvey** [pouchdb/pouchdb#5207]
I wanted a bug to track the discussion for getting this merged / released. I am going to open a seperate issue for the implementation of pouchdb-find just to not confuse the issue, this is to figure out what we want to do with the adapter
- [x] Merge non adapter specific changes (https://github.com/pouchdb/pouchdb/pull/5208)
- [x] Fix last 3 skipped tests, merge changes to tests
- [x] Ensure we have tests ensuring local documents are skipped in changes
- [x] Ensure persist update_seq test is working correctly
- [x] Merge to mono repo, undocumented / unreleased
- [x] Implement pouchdb-find
- [x] Make work in current Safari?

**Comment by nolanlawson** [comment]
As a suggestion: maybe the adapter name should be `'indexeddb'`? This would allow the `'idb'` and `'indexeddb'` adapters to live side-by-side, while not burdening us forever with an funky name like `'idb2'` or `'idb-next'` or such.

After the monorepo release, I foresee some users have an adapter order like `'indexeddb'` `'idb'` `'websql'`, since idb-next gives performance improvements but doesn't support IE/Edge/old Android/etc..

**Comment by daleharvey** [comment]
`indexeddb` sounds fine by me, I was going to need to look at that again @ https://github.com/pouchdb/pouchdb/pull/4984/files#diff-92135614f5c1d478bba08fcf500eb83dR19
 
I am not certain how we want to release this, fairly sure we dont want to ship it as an additional adapter to the current 2, thats a lot of extra code + complexity for little benefit. I am confident that we can have this adapter supported in ie (its currently working in safari albiet unreliably, with no special safari specific work). Releasing it as evergreen (ie no upgrades) is very tempting but leaves a lot of current users in the lurch, I think I will have to write a migration for this :(

Need to remember that this will also be dealing with migrations from webSQL to indexedDB, I do plan on making the migration code easy to remove from the build so we can have an indication of exactly how much it is costing us

**Comment by nolanlawson** [comment]
I'm not proposing shipping it in `pouchdb` (for now), but rather as `pouchdb-adapter-indexeddb-next` or some such. Users can use it as part of a custom build, e.g.:

```js
var PouchDB = require('pouchdb-core')
  .plugin('pouchdb-adapter-indexeddb-next');
```
As for migrations, in the case of this one I think we should write a sub-package called `pouchdb-migrate` that allows users to explicitly migrate, e.g.:

```js
var migrate = require('pouchdb-migrate');
var dbName = 'foo';
migrate('foo').then(/* ... */);
```

Users should be expected to handle this themselves, because it's a big change and as you say, we can't know if they're running changes/replication concurrently, so they need to stop the world and do the migration.

I measured the size of the idb/websql migrations once; I believe it was around 1kB min+gz for each one.

**Comment by nolanlawson** [comment]
Just occurred to me that this is a really tricky feature to put out in "beta" because it writes to hard disks. 😕  I guess we better get the format right the first time.

**Comment by daleharvey** [comment]
Yup, I definitely want to let this bake for a while and not rush it, maintaining migrations 'forever' is not fun. 

@nolanlawson I got this to a place where is seems like it should be mostly working @ https://github.com/pouchdb/pouchdb/tree/new-idb-next, I dont really know how to debug what is going wrong from here though. getting 

```
build error
Error: Cannot find module 'pouchdb-adapter-idb-next' from '/Users/daleharvey/src/pouchdb/packages/pouchdb-browser/src'
    at /Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:46:17
    at process (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:92:31)
    at /Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

in `npm build` and 

```
~/src/pouchdb (new-idb-next)$ ./bin/build-module.js ./packages/pouchdb-adapter-idb-next/
build-module.js error
Error: Cannot find module 'pouchdb-binary-utils' from '/Users/daleharvey/src/pouchdb/packages/pouchdb-adapter-idb-next/src'
    at /Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:46:17
    at process (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:92:31)
    at /Users/daleharvey/src/pouchdb/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by daleharvey** [comment]
I found the latter issue, thought I already had `pouchdb-binary-utils` in package.json but didnt

```
~/src/pouchdb (new-idb-next)$ ./bin/build-module.js ./packages/pouchdb-adapter-idb-next/
  ✓ wrote pouchdb-adapter-idb-next/lib/index.js in vanilla mode
``` 
Now seems to work find, but same problem with `npm run build`

**Comment by daleharvey** [comment]
Found it, also needed to change `package.json` in `pouchdb-browser`, ok hopefully it should be testable now

**Comment by daleharvey** [comment]
> Users should be expected to handle this themselves, because it's a big change and as you say, 
> we can't know if they're running changes/replication concurrently, so they need to stop the world 
> and do the migration.

Thinking about this more I agree, I am not even convinced a seamless migration as we know it is going to be possible because its going to involve transactions that span webSQL + indexedDB. I am beginning to think that migrating via replication is going to be by far the easiest method, we can make a build which includes both releases and have a helper to migrate data into the new adapter via migration, new users dont need to worry about anything, migrating users can make informed tradeoffs about how long they are going to support their users and how critical the local data is (ie having to resync from a server one off is often not a big deal) plus have a nice easy way to migrate (forever if needed) if data is critical

**Comment by nolanlawson** [comment]
> Found it, also needed to change package.json in pouchdb-browser, ok hopefully it should be testable now

What's the change?

**Comment by nolanlawson** [comment]
ced745440c239b98911fd51130f56aa6e8fadce4 and 743983acceeb4c373d53b29bd0cd6abffd9273c6 were merged. leaving this issue open for now

**Comment by nolanlawson** [comment]
No prob ^. Would love to start playing around with it more. :)

**Comment by natcohen** [comment]
Any plan to release this as a plugin for v6?

**Comment by nolanlawson** [comment]
It’s a “secret” build, but yeah: https://unpkg.com/pouchdb@6.0.5/dist/pouchdb-next.js

Don’t bet the farm on this build, by the way. We make no guarantees of semver/migration on this.

– Nolan

**Comment by garrensmith** [comment]
This should probably stay open until we finish idb-next

________________________________

**Comment by SCdF** [comment]
Implement find in idbnext: https://github.com/pouchdb/pouchdb/pull/7547

**Comment by SCdF** [comment]
Since find is nearly ready to roll, here are my thoughts on things we'd need to do before idbnext was made the default adapter:
- [ ] Work out what migration approach we want to take between idb and idbnext (automatic internal migration, automatic replication-based migration, keeping both adapters and just using the new one for new dbs, forced manual migration via erroring if you try to use an old idb db, etc)
- [ ] Look into current performance regressions (most things are faster in idbnext, but a couple of interactions are slowly, I think because we're not reusing transactions as intended by the abstract layer)
- [ ] Change our travis integration so tests are run against this adapter instead of the current one (this may happen naturally when it we change the build to make it the default)
- [ ] Either officially drop IE11 support (there weirdness around instantiating idb connections with non-hardcoded version numbers), or work out how to fix it

Let me know if that makes sense, and if there is anything else that we should be considering.

My personal plan is going to be creating a discussion ticket about the first one (there are lots of choices here, all of them not amazing), work on the next two and ignore the last one ;-)

**Comment by dholth** [comment]
Also having trouble in Safari. But otherwise it is many, many times faster than idb.
