### ISSUE TITLE
Checklist: deprecations for 6.0.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#5586]
Following up from #5342, let's track what we need finished before we can publish 6.0.0:

- [x] remove `new PouchDB().then()` (https://github.com/pouchdb/pouchdb/pull/5319)
- [x] remove `db.put(doc, id, rev)` (https://github.com/pouchdb/pouchdb/pull/5311)
- [x] remove SQLite Plugin support, create separate plugin (#5519)
- [x] remove `optionalDependencies` (replaced with custom builds) (#5590)
- [x] remove `extras` (ditto)
- [ ] ~~remove everything from `dist` except `pouchdb.js`, `pouchdb.min.js`, and `pouchdb.next.js`~~
- [ ] ~~move other `dist` files to sub-packages, each sub-package has its own `dist`~~

Removing lie, defaults, and prefix seem controversial, so I propose we punt on those for now. For removing `skipSetup`/`skip_setup` and `returnDocs`/`return_docs` etc. I'd say the cost of maintaining backwards compat is lower than the cost of removing them, so I propose punting on that as well. Dropping bower/jsdelivr/cdnjs support also seems like more work than its worth right now. Ditto for removing pouchdb-http and `db` from the leveldb adapters.

I'd also like to consider publishing 6.0.0 as with a `dist-tag` of `beta`, which is a trick @boennemann explained to me that allows us to publish a "preview" version without making it the version that gets installed by default when you do `npm install pouchdb`.

**Comment by nolanlawson** [comment]
In case it's not clear, I intend to tackle all of those unchecked checkboxes, so unless someone else wants to take them up, I'm licking that cookie. :) The recent Lerna removals (#5550, #5583) were an effort on my part to simplify the build code in preparation for the deprecations.

**Comment by DanielMaly** [comment]
No plans to include #5322?

**Comment by nolanlawson** [comment]
After talking with @gr2m and thinking about this a bit more, I think we should skip removing `dist` from the core package. A few reasons:

1. It's been too long since a release, let's get 6.0.0 out
2. Removing it would require tons of changes to our tests which largely depend on loading from `dist`
3. It's probably more complicated for users anyway. `dist` is designed for non-power users, and those users probably don't want to go hunting in sub-packages to find something.

So based on that, I'll cross out the last two items. I say once `extras` is out, we can release. I'll look into doing a npm prerelease (using dist-tags) this week or weekend. @daleharvey do you agree?

**Comment by garrensmith** [comment]
+1 from me

All misspelling thanks to my iPhone.




On Tue, Aug 30, 2016 at 5:02 PM +0200, "Nolan Lawson" <notifications@github.com> wrote:












After talking with @gr2m and thinking about this a bit more, I think we should skip removing dist from the core package. A few reasons:


It's been too long since a release, let's get 6.0.0 out
Removing it would require tons of changes to our tests which largely depend on loading from dist

It's probably more complicated for users anyway. dist is designed for non-power users, and those users probably don't want to go hunting in sub-packages to find something.




So based on that, I'll cross out the last two items. I say once extras is out, we can release. I'll look into doing a npm prerelease (using dist-tags) this week or weekend. @daleharvey do you agree?

**Comment by gr2m** [comment]
The "remove `extras`" is ready via https://github.com/pouchdb/pouchdb/pull/5591 I think

**Comment by nolanlawson** [comment]
6.0.3 will be released today, which will be the "official" release. (6.0.1 and 6.0.2 were tagged as beta.)
