### ISSUE TITLE
pouchdb-find monorepo merge mega-issue

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6289]
Tasks remaining:

- [x] merge the code ( #3538 )
- [x] merge the issues ( #6252 )
- [x] merge the documentation ( #6251 )

**Comment by garrensmith** [comment]
Done!
