### ISSUE TITLE
Checklist for PouchDB 7.0.0

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#6356]
### Summary

We released 6.0.0 in September 2016, and 5.0.0 in December 2015. I agree with Tom Dale that [SemVer shouldn't mean more breaking changes](https://medium.com/@tomdale/semver-shouldnt-mean-more-breaking-changes-abfb7990dbab), so to keep us around ~1 major release per year, I'd propose a 7.0.0 release later this year.

I think the ideal strategy is to cram as many breaking changes as possible into a few infrequent releases. You don't want users to have to wonder: "Hmmm, in v7 they removed this, and in v8 they removed that, and in v9 they removed another thing, so if I'm on v5 and want to upgrade to v10...". [Keep it simple](https://github.com/pouchdb/pouchdb/wiki/Breaking-changes).

Following up on discussion in https://github.com/pouchdb/pouchdb/issues/6019, this is a living list of breaking changes for PouchDB 7.0.0. Please comment here if anything concerns you, or if there are other changes you'd like to add.

### TODOs

- [ ] extract `PouchDB.debug()` as its own plugin (saves ~2KB) (https://github.com/pouchdb/pouchdb/pull/6158)
- [ ] extract `pouchdb-mapreduce` from `pouchdb-core` (saves ~4.5KB)
- [ ] remove `db.type()` (https://github.com/pouchdb/pouchdb/pull/6346)
- [ ] map filters require strict mode (https://github.com/pouchdb/pouchdb/pull/6247)

### Nice-to-haves, may not make it

- [ ] extract polyfills (doesn't seem worth it yet: https://github.com/pouchdb/pouchdb/issues/6019#issuecomment-287798079)
- [ ] deterministic revs by default (I'm worried about perf overhead, docs complexity) (https://github.com/pouchdb/pouchdb/issues/4642)
- [ ] extract replication/changes filters as their own plugin (https://github.com/pouchdb/pouchdb/issues/6355)
- [ ] remove/rename `PouchDB.preferredAdapters`, `PouchDB.prefix`, `PouchDB.adapters` (high breakage risk, low benefit)
- [ ] `db` object should not be a promise for itself – causes "circular promise" errors, unnecessary now that the constructor is stateless **_(new)_**
- [ ] extract `PouchDB.defaults()` as its own plugin (saves little, but hard to maintain) **_(moved to "nice to have," seems this may be tricky)_**

### Planning

In terms of strategy, I think we should create a separate branch called `breaking` and keep it rebased against `master`. That way, we don't need to worry about merging breaking changes into `master`, or feel tempted to do a major release prematurely.

My hunch is that 7.0.0 will be the last major release before `idb-next` lands in 8.0.0. I think IDB in Safari is still not widespread enough to start focusing on it yet (10.1 isn't even officially released yet, there are bugs: https://github.com/pouchdb/pouchdb/issues/6349), and we need to work on perf of `idb-next` and IE/Edge compatibility (I'm happy to take responsibility for that; it may take the form of a separate plugin like [idb-iegap](https://github.com/dfahlander/idb-iegap)).

We should probably also use [dist-tags](https://docs.npmjs.com/cli/dist-tag) to start shipping alpha versions of 7.0.0 to npm before it's officially released. Babel, Webpack, and many other projects have had success with this strategy.

**Comment by garrensmith** [comment]
The other thing I would like for 7.0 is to take pouchdb-find out of beta. I think pouchdb-find is reaching a pretty stable state and I'm happy to do some work over the next few weeks to close out the final list of bugs.

**Comment by nolanlawson** [comment]
Yup, I agree. No reason to call it "beta" anymore. The actual indexing is 100% solid because it's based on pouchdb-abstract-mapreduce. The only thing that's still incomplete is the query language, but that's less of a big deal because it can always be fixed later, without requiring data migration.

**Comment by lifaon74** [comment]
About polyfill, I think it could be great to remove them from core for 2 reasons : 
1) Some user maybe target only last browsers/nodejs expecting a minimum size
2) Most of the time, front end developpers (in browser) use core-js or their own polyfills, so it could result in unecessary code redondancy.

By the way, guys you do a great job, thanks to you.

**Comment by nolanlawson** [comment]
> Most of the time, front end developpers (in browser) use core-js or their own polyfills

I'm not sure this is actually the case. I don't have data, but my hunch is that since Webpack/Browserify are new technologies, most webdevs are still using old-fashioned `<script>` tags or something similar.

I think it's important to strike a balance between "works out of the box" for beginners and "I can customize to my liking" for experts. Take a look at #6377 where I'm trying to make this a bit more explicit without needing to yank out features for absolutely everybody. 😃

**Comment by lifaon74** [comment]
I aggree on the fact that beginners will use <script> tag. But for professional, it's mandatory use use bundler (like rollup => strong compression and one output file), minimifier, tests, automation (ex: gulp), etc... All peoples dont live in european or north american countries. India or China represent a big market (billions of people) and still have a slow connection... Same for mobile devices...

For a "works out of the box" you could provide some king of "pouchdb-web-full.js" which could import pouchdb-core, pouchdb-mapreduce, shims, etc...

**Comment by nolanlawson** [comment]
@lifaon74 Does the proposed `pouchdb-lite` work well for you? Typically I prefer for the default to be "works out of the box", since beginners often don't read very deeply in the documentation before they start to use it. Your points are valid, but if newbies can't quickly get up-and-running with an open-source project they will just use another one.

**Comment by ntodd** [comment]
>  I think IDB in Safari is still not widespread enough to start focusing on it yet (10.1 isn't even officially released yet, there are bugs: #6349)

@nolanlawson Since iOS is now at 10.3 (almost 11.0) and #6349 is closed, is there anything still holding up IDB support in later versions of Safari?

**Comment by daleharvey** [comment]
I think the current blocker is saucelabs supporting a late enough version of safari, I think last time I checked they still only support 10.1, we cant release anything big like that unless it is tested in automation

**Comment by daleharvey** [comment]
Opened a new issue for this as almost a year gone by and the issue priority is different now

**Comment by daleharvey** [comment]
https://github.com/pouchdb/pouchdb/issues/6946
