### ISSUE TITLE
EPIC: Preparing a punch of incremental PR's:

### ISSUE THREAD

**Issue by lemanschik** [pouchdb/pouchdb#8661]
## Can be done incremental
- [ ] remove adapter gets replaced by internal message channels and optional additional [ECMAScript Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)
- [ ] remove the dependency on eventEmitter and destroy patching from node using [ECMAScript Broadcast Channel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)
- [ ] New Correct Build Process ESNext Only if a user runs in legacy env he needs to Polyfill.
- [ ] Splitting platforms via pouchdb-platform which implements runtime bindings in a central place to get easier maintainability
- [ ] New versioning based on the dependencies and hashes. Managing own version references leads always to errors.
- [ ] publishing /lib folder on git later when all changes are stable /lib gets the new development and published version the development version will be run able without additonal build steps.
- [ ] replace md5-spark and all other crypto hashing with "hash-wasm"
- [ ] replace leveldb with leveldb-wasm
- [ ] implement opfs / fs as nativ default storage backend. all other backends will implement the same api

## Deprecation next Major
TODO:

## Adoption Strategie
lib + platform === pouchdb
- Release pouchdb-platform
- Release pouchdb-lib
- Update docs once stabilised.
